export const GET_PROJECT = "GET_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const PROJECT_ERROR = "PROJECT_ERROR";
